name: flutter_single_getx_api_v2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.4
  get: 4.6.6
  get_storage: ^2.1.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  logger: ^2.0.2+1
  lottie: ^2.7.0
  persistent_bottom_nav_bar_v2: ^4.2.8
  badges: ^3.1.2
  intl: ^0.19.0
  path_provider: ^2.1.1
  dio: ^5.4.0
  http: ^1.1.2
  file_utils: ^1.0.1
  flutter_cache_manager: ^3.3.1
  open_filex: ^4.3.4
  permission_handler: ^11.1.0
  flutter_calendar_carousel: ^2.4.2
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  device_info_plus: ^9.1.1
  shared_preferences: ^2.2.2
  pusher_channels_flutter: ^2.2.0
  url_launcher: ^6.2.3
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^16.3.1+1
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  rxdart: ^0.27.7
  edge_alerts: ^0.0.1
  jitsi_meet_flutter_sdk: ^0.1.9
  #  eko_jitsi: ^1.3.8
  pdf_flutter:
    git: https://github.com/erluxman/pdf_flutter

  # Payment Gateways
  flutter_stripe: ^10.0.0
  stripe_sdk: ^5.0.0
  flutter_paypal_checkout: ^1.0.1
  flutter_paystack: ^1.0.7

  flutter:
    sdk: flutter

dependency_overrides:
  http: ^0.13.5
  file_picker: ^5.1.6
  intl: ^0.18.1
  stripe_android: 9.5.0+1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - assets/images/
    - assets/config/
    - assets/icons/student/
    - assets/icons/teacher/
    - assets/icons/parents/
    - assets/icons/admin/
    - assets/svg/student/


fonts:
  - family: poppins
    fonts:
      - asset: fonts/poppins_medium.ttf
        weight: 100
      - asset: fonts/poppins_bold.ttf
        weight: 200
      - asset: fonts/poppins_light.ttf
        weight: 300
      - asset: fonts/poppins_regular.ttf
        weight: 400
      - asset: fonts/poppins_semibold.ttf
        weight: 500