name: flutter_single_getx_api_v2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.4
  get: 4.6.6
  get_storage: ^2.1.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  logger: ^2.0.2+1
  lottie: ^2.6.0
  persistent_bottom_nav_bar_v2: ^4.2.8
  badges: ^3.1.2
  intl: ^0.18.1
  dropdown_button2: ^2.3.9
  themify_flutter:
    path: ./themify_flutter

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/config/
    - assets/images/
    - assets/config/
    - assets/icons/student/
    - assets/icons/teacher/
    - assets/icons/parents/
    - assets/icons/admin/
    - assets/svg/student/


fonts:
  - family: poppins
    fonts:
      - asset: fonts/poppins_medium.ttf
        weight: 100
      - asset: fonts/poppins_bold.ttf
        weight: 200
      - asset: fonts/poppins_light.ttf
        weight: 300
      - asset: fonts/poppins_regular.ttf
        weight: 400
      - asset: fonts/poppins_semibold.ttf
        weight: 500