// ignore_for_file: constant_identifier_names

part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SPLASH = _Paths.SPLASH;
  static const SECONDARY_SPLASH = _Paths.SECONDARY_SPLASH;
  static const LOGIN = _Paths.LOGIN;
  static const PROFILE = _Paths.PROFILE;
  static const SYLLABUS = _Paths.SYLLABUS;
  static const DASHBOARD = _Paths.DASHBOARD;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const PROFILE_EDIT = _Paths.PROFILE_EDIT;
  static const STUDENT_HOMEWORK = _Paths.STUDENT_HOMEWORK;
  static const ROUTINE = _Paths.ROUTINE;
  static const STUDY_MATERIALS = _Paths.STUDY_MATERIALS;
  static const ASSIGNMENT = _Paths.ASSIGNMENT;
  static const SETTINGS = _Paths.SETTINGS;
  static const SCHEDULE = _Paths.SCHEDULE;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const RESULT = _Paths.RESULT;
  static const ACTIVE_EXAM = _Paths.ACTIVE_EXAM;
  static const EXAMINATION = _Paths.EXAMINATION;
  static const ONLINE_EXAM = _Paths.ONLINE_EXAM;
  static const EXAM_RESULT = _Paths.EXAM_RESULT;
  static const OTHER_DOWNLOADS = _Paths.OTHER_DOWNLOADS;
  static const DORMITORY = _Paths.DORMITORY;
  static const APPLY_LEAVE = _Paths.APPLY_LEAVE;
  static const LEAVE_LIST = _Paths.LEAVE_LIST;
  static const LEAVE = _Paths.LEAVE;
  static const ATTENDANCE = _Paths.ATTENDANCE;
  static const NOTICE = _Paths.NOTICE;
  static const SUBJECTS = _Paths.SUBJECTS;
  static const TEACHER = _Paths.TEACHER;
  static const LIBRARY = _Paths.LIBRARY;
  static const BOOK_LIST = _Paths.BOOK_LIST;
  static const BOOK_ISSUED = _Paths.BOOK_ISSUED;
  static const TRANSPORT = _Paths.TRANSPORT;
  static const FEES = _Paths.FEES;
  static const CHAT = _Paths.CHAT;
  static const CHAT_SEARCH = _Paths.CHAT_SEARCH;
  static const STUDENT_SEARCH_ATTENDANCE = _Paths.STUDENT_SEARCH_ATTENDANCE;
  static const STUDENT_LESSON_PLAN = _Paths.STUDENT_LESSON_PLAN;
  static const STUDENT_SEARCH_SUBJECT_ATTENDANCE =
      _Paths.STUDENT_SEARCH_SUBJECT_ATTENDANCE;
  static const FORGET_PASSWORD = _Paths.FORGET_PASSWORD;
  static const STUDENT_WALLET = _Paths.STUDENT_WALLET;
  static const BLOCKED_USERS = _Paths.BLOCKED_USERS;
  static const STAFF = _Paths.STAFF;
  static const STAFF_LIST = _Paths.STAFF_LIST;
  static const STAFF_INDIVIDUAL_DETAILS = _Paths.STAFF_INDIVIDUAL_DETAILS;
  static const SINGLE_CHAT = _Paths.SINGLE_CHAT;
  static const STUDENT_CLASS = _Paths.STUDENT_CLASS;
  static const ADMIN_LEAVE = _Paths.ADMIN_LEAVE;
  static const ADMIN_DORMITORY = _Paths.ADMIN_DORMITORY;
  static const ADMIN_ADD_DORMITORY = _Paths.ADMIN_ADD_DORMITORY;
  static const ADMIN_ADD_ROOM = _Paths.ADMIN_ADD_ROOM;
  static const ADMIN_ROOM_LIST = _Paths.ADMIN_ROOM_LIST;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SPLASH = '/splash';
  static const SECONDARY_SPLASH = '/secondary-splash';
  static const LOGIN = '/login';
  static const PROFILE = '/profile';
  static const SYLLABUS = '/syllabus';
  static const DASHBOARD = '/dashboard';
  static const NOTIFICATION = '/notification';
  static const PROFILE_EDIT = '/profile-edit';
  static const STUDENT_HOMEWORK = '/student-homework';
  static const ROUTINE = '/routine';
  static const STUDY_MATERIALS = '/study-materials';
  static const ASSIGNMENT = '/assignment';
  static const SETTINGS = '/settings';
  static const SCHEDULE = '/schedule';
  static const CHANGE_PASSWORD = '/change-password';
  static const RESULT = '/result';
  static const ACTIVE_EXAM = '/active-exam';
  static const EXAMINATION = '/examination';
  static const ONLINE_EXAM = '/online-exam';
  static const EXAM_RESULT = '/exam-result';
  static const OTHER_DOWNLOADS = '/other-downloads';
  static const DORMITORY = '/dormitory';
  static const APPLY_LEAVE = '/apply-leave';
  static const LEAVE_LIST = '/leave-list';
  static const LEAVE = '/leave';
  static const ATTENDANCE = '/attendance';
  static const NOTICE = '/notice';
  static const SUBJECTS = '/subjects';
  static const TEACHER = '/teacher';
  static const LIBRARY = '/library';
  static const BOOK_LIST = '/book-list';
  static const BOOK_ISSUED = '/book-issued';
  static const TRANSPORT = '/transport';
  static const FEES = '/fees';
  static const CHAT = '/chat';
  static const CHAT_SEARCH = '/chat-search';
  static const STUDENT_SEARCH_ATTENDANCE = '/student-search-attendance';
  static const STUDENT_LESSON_PLAN = '/student-lesson-plan';
  static const STUDENT_SEARCH_SUBJECT_ATTENDANCE =
      '/student-search-subject-attendance';
  static const FORGET_PASSWORD = '/forget-password';
  static const STUDENT_WALLET = '/student-wallet';
  static const BLOCKED_USERS = '/blocked-users';
  static const STAFF = '/staff';
  static const STAFF_LIST = '/staff-list';
  static const STAFF_INDIVIDUAL_DETAILS = '/staff-individual-details';
  static const SINGLE_CHAT = '/single-chat';
  static const STUDENT_CLASS = '/student-class';
  static const ADMIN_LEAVE = '/admin-leave';
  static const ADMIN_DORMITORY = '/admin-dormitory';
  static const ADMIN_ADD_DORMITORY = '/admin-add-dormitory';
  static const ADMIN_ADD_ROOM = '/admin-add-room';
  static const ADMIN_ROOM_LIST = '/admin-room-list';
}
